service: aws-dynamodb

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-southeast-1

functions:
  AddEditItem:
    handler: AddEditItem.handler
    events:
      - http:
          path: table/addedititem
          method: post
          cors: true
  DeleteItem:
    handler: DeleteItem.handler
    events:
      - http:
          path: table/deleteitem
          method: post
          cors: true
  GetItem:
    handler: GetItem.handler
    events:
      - http:
          path: table/getitem
          method: get
          cors: true
  QueryItems:
    handler: QueryItems.handler
    events:
      - http:
          path: table/queryitems
          method: get
          cors: true
  ScanItems:
    handler: ScanItems.handler
    events:
      - http:
          path: table/scanitems
          method: get
          cors: true

resources:
  Resources:
    MusicTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: prefix--sample-table
        AttributeDefinitions:
          - AttributeName: Artist
            AttributeType: S
          - AttributeName: SongTitle
            AttributeType: S
        KeySchema:
          - AttributeName: Artist
            KeyType: HASH
          - AttributeName: SongTitle
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5