
service: sonab-aws-lambda-test
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-1
  stage: dev
functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: users/create
        method: get
